name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_a2c9c8dd-dddb-4f8a-b843-f31ac7dfcfc4 }}
          GH_TOKEN: ${{ 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 }}
